#ifndef SERVERFUNCTION_H_INCLUDED
#define SERVERFUNCTION_H_INCLUDED

DWORD WINAPI FtpTcpServer(LPVOID lpParamter);
DWORD WINAPI FtpUdpServer(LPVOID lpParamter);
DWORD WINAPI WebTcpServer(LPVOID lpParamter);

#endif // SERVERFUNCTION_H_INCLUDED
